### ISSUE TITLE
Expected EOF Found } Error On Line 322

### ISSUE THREAD

**Issue by The-Bit-One** [The-Bit-One/Asteroid_Dodge#1]

**Comment by ad101-lab** [comment]
# How did you fix it???????????

**Comment by The-Bit-One** [comment]
I posted my code on the forums and some dude fixed it

Riley Herchert

On Feb 26, 2020, at 16:26, ad101-lab <notifications@github.com> wrote:

﻿How did you fix it???????????

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/The-Bit-One/Asteroid_Dodge/issues/1?email_source=notifications&email_token=AOVBKNFOSNCYCBOCWDM6XBLRE33DTA5CNFSM4K3TBH72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENCJIAY#issuecomment-591696899>,
or unsubscribe
